[issue-14] create Account Menu and Page
alecherryy/cooks-books-app pull request #60
Opened 2021-04-16 19:32 UTC by alecherryy

2021-04-16 23:08 UTC, rileyhgrant approved these changes
Looks dope! Any comments I left are just comments haha. Very nicely done.

2021-04-16 23:08 UTC, rileyhgrant commented on src/index.js
> +import { AuthProvider } from './Auth';
ah cool, makes more sense to put it here!

2021-04-16 23:08 UTC, rileyhgrant commented on src/stories/components/AccountMenu/AccountMenu.js
> +      // setError('');
ah cool, so we'll add a setError at some point to show the user whatever error firebase auth spits back. word.

2021-04-16 23:08 UTC, rileyhgrant commented on src/stories/components/AccountMenu/styles.scss
> +    .account-menu__text {
looks pretty sliiiick

2021-04-17 05:07 UTC, looper-m requested changes

2021-04-17 05:07 UTC, looper-m commented on src/stories/components/MainMenu/MainMenu.js
> +            currentUser.fullName
`currentUser` does not have a `fullName`. There is an attribute `displayName` but thats just null.
The profile always has a `username` and I left `email` in `else` just as a safety net

2021-04-21 02:15 UTC, merged